CREATE SCHEMA IF NOT EXISTS ORGANIZATION;

DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS EMPLOYEE_PROJECT;

CREATE TABLE EMPLOYEE
(EMPCODE VARCHAR(10) NOT NULL );
ALTER TABLE EMPLOYEE
ADD CONSTRAINT PK_E PRIMARY KEY (EMPCODE);

CREATE TABLE DEPARTMENT
( DEPTCODE VARCHAR(10) NOT NULL, EMPCODE  VARCHAR(10) NOT NULL);
ALTER TABLE DEPARTMENT
ADD (CONSTRAINT PK_D PRIMARY KEY (DEPTCODE),
          CONSTRAINT FK_DE FOREIGN KEY (EMPCODE) REFERENCES EMPLOYEE(EMPCODE) );

CREATE TABLE PROJECT
(PROJCODE VARCHAR(10) NOT NULL, DEPTCODE VARCHAR(10) NOT NULL);
ALTER TABLE PROJECT
ADD (CONSTRAINT PK_P PRIMARY KEY (PROJCODE, DEPTCODE),
	 CONSTRAINT FK_PD FOREIGN KEY (DEPTCODE) REFERENCES DEPARTMENT(DEPTCODE) );

-- table to exclusively hold employee-project relation --
CREATE TABLE EMPLOYEE_PROJECT
(EMPCODE VARCHAR(10) NOT NULL, PROJCODE VARCHAR(10) NOT NULL, DEPTCODE VARCHAR(10) NOT NULL);
ALTER TABLE EMPLOYEE_PROJECT
ADD (CONSTRAINT PK_EP PRIMARY KEY (EMPCODE, PROJCODE, DEPTCODE),
	 CONSTRAINT FK_EPE FOREIGN KEY (EMPCODE) REFERENCES EMPLOYEE(EMPCODE),
	 CONSTRAINT FK_EPPD FOREIGN KEY (PROJCODE, DEPTCODE) REFERENCES EMPLOYEE_PROJECT(PROJCODE, DEPTCODE) );